export interface Bairro {
  name: string;
  slug: string;
}

export const bairrosGuarulhos: Bairro[] = [
  { name: 'Água Azul', slug: 'agua-azul' },
  { name: 'Água Chata', slug: 'agua-chata' },
  { name: 'Aracília', slug: 'aracilia' },
  { name: 'Bananal', slug: 'bananal' },
  { name: 'Bela Vista', slug: 'bela-vista' },
  { name: 'Bom Clima', slug: 'bom-clima' },
  { name: 'Bonsucesso', slug: 'bonsucesso' },
  { name: 'Cabuçu', slug: 'cabucu' },
  { name: 'Cabuçu de Cima', slug: 'cabucu-de-cima' },
  { name: 'Capelinha', slug: 'capelinha' },
  { name: 'CECAP', slug: 'cecap' },
  { name: 'Centro', slug: 'centro' },
  { name: 'Cocaia', slug: 'cocaia' },
  { name: 'Cumbica', slug: 'cumbica' },
  { name: 'Fátima', slug: 'fatima' },
  { name: 'Fortaleza', slug: 'fortaleza' },
  { name: 'Gopoúva', slug: 'gopouva' },
  { name: 'Invernada', slug: 'invernada' },
  { name: 'Itaim', slug: 'itaim' },
  { name: 'Itapegica', slug: 'itapegica' },
  { name: 'Jardim Vila Galvão', slug: 'jardim-vila-galvao' },
  { name: 'Lavras', slug: 'lavras' },
  { name: 'Macedo', slug: 'macedo' },
  { name: 'Maia', slug: 'maia' },
  { name: 'Mato das Cobras', slug: 'mato-das-cobras' },
  { name: 'Monte Carmelo', slug: 'monte-carmelo' },
  { name: 'Morro Grande', slug: 'morro-grande' },
  { name: 'Morros', slug: 'morros' },
  { name: 'Paraventi', slug: 'paraventi' },
  { name: 'Picanço', slug: 'picanco' },
  { name: 'Pimentas', slug: 'pimentas' },
  { name: 'Ponte Grande', slug: 'ponte-grande' },
  { name: 'Porto da Igreja', slug: 'porto-da-igreja' },
  { name: 'Presidente Dutra', slug: 'presidente-dutra' },
  { name: 'Sadokim', slug: 'sadokim' },
  { name: 'São João', slug: 'sao-joao' },
  { name: 'São Roque', slug: 'sao-roque' },
  { name: 'Taboão', slug: 'taboao' },
  { name: 'Tanque Grande', slug: 'tanque-grande' },
  { name: 'Torres Tibagy', slug: 'torres-tibagy' },
  { name: 'Tranquilidade', slug: 'tranquilidade' },
  { name: 'Várzea do Palácio', slug: 'varzea-do-palacio' },
  { name: 'Vila Augusta', slug: 'vila-augusta' },
  { name: 'Vila Barros', slug: 'vila-barros' },
  { name: 'Vila Galvão', slug: 'vila-galvao' },
  { name: 'Vila Rio de Janeiro', slug: 'vila-rio-de-janeiro' }
];
